@startuml Tetris

skinparam monochrome true
hide empty members

class PlayState {
  board
  powerUps
  level
  score
  linesCleared
  enter()
  exit()
  update()
  render()
  checkVictory()
  checkGameOver()
  handleCollisions()
  generateBlock()
}

class Board {
  blocks
  update()
  render()
  clear()
}

class Block {
  boardPosition
  canvasPosition
  update()
  render()
  move()
  rotate()
}

class BlockI {
  render()
}

class BlockO {
  render()
}

class BlockT {
  render()
}

class BlockS {
  render()
}

class BlockL {
  render()
}

class BlockZ {
  render()
}

class BlockJ {
  render()
}

class PowerUp {
  update()
  hit()
  render()
}

class TimePowerUp {
  hit()
  render()
}

class SpeedPowerUp {
  hit()
  render()
}

class BlockFactory {
  createInstance()
}

class PowerUpFactory {
  createInstance()
}

class Position {
  x
  y
}

enum Direction {
  LEFT
  RIGHT
  DOWN
}

PlayState -- "1" Board
PlayState -- "*" PowerUp
Board     -- "*" Block

PowerUp <|-- TimePowerUp
PowerUp <|-- SpeedPowerUp

Block <|-- BlockI
Block <|-- BlockO
Block <|-- BlockT
Block <|-- BlockS
Block <|-- BlockL
Block <|-- BlockZ
Block <|-- BlockJ

@enduml
